services:
  bot:
    build: .
    restart: always
    environment:
      - DISCORD_BOT_SECRET=${DISCORD_BOT_SECRET}
    network_mode: "host"
    volumes:
      - gallery_uploads:/bot/uploads

volumes:
  gallery_uploads: