services:
  sneaksbot:
    build: .
    restart: unless-stopped
    env_file: 
      - ".env"
    network_mode: "host"
    volumes:
      - gallery_uploads:/bot/uploads
    container_name: sneaksbot

volumes:
  gallery_uploads:
    external: true